# This is in dollars, we convert when calculating amount left
GRANT_DICTS = {"3015002026": {"5000105": {"Amount": 6785, "Shared": 1, "Description": "Write your description here"},
                              "5000206": {"Amount": 6785, "Shared": 1, "Description": "Write your description here"},
                              "5000209": {"Amount": 6785, "Shared": 1, "Description": "Write your description here"},
                              "6001002": {"Amount": 11699, "Shared": 3, "Description": "Write your description here"},
                              "6001003": {"Amount": 1, "Shared": 3, "Description": "Write your description here"},
                              "6005005": {"Amount": 0, "Shared": 12, "Description": "Write your description here"},
                              "6005006": {"Amount": 0, "Shared": 12, "Description": "Write your description here"},
                              "6005021": {"Amount": 31460, "Shared": 12, "Description": "Write your description here"},
                              "6005022": {"Amount": 0, "Shared": None, "Description": "Write your description here"},
                              "6010001": {"Amount": 0, "Shared": None, "Description": "Write your description here"},
                              "5300003": {"Amount": 2585, "Shared": 1, "Description": "Write your description here"},
                              "7030100": {"Amount": 0, "Shared": None, "Description": "Write your description here"},
                              "6013436": {"Amount": 440, "Shared": None, "Description": "Write your description here"}
                             },
               "3011003051": {"5000105": {"Amount": 20000, "Shared": 1, "Description": "Write your description here"},
                              "5000106": {"Amount": 0, "Shared": 1, "Description": "Write your description here"},
                              "5000206": {"Amount": 10000, "Shared": 1, "Description": "Write your description here"},
                              "5000209": {"Amount": 10000, "Shared": 1, "Description": "Write your description here"},
                              "6001002": {"Amount": 6000, "Shared": None, "Description": "Write your description here"},
                              "6003000": {"Amount": 1000, "Shared": 2, "Description": "Write your description here"},
                              "6005005": {"Amount": 0, "Shared": 1, "Description": "Write your description here"},
                              "6005006": {"Amount": 0, "Shared": 1, "Description": "Write your description here"},
                              "6005021": {"Amount": 97752, "Shared": 1, "Description": "Write your description here"},
                              "6005022": {"Amount": 24000, "Shared": 12, "Description": "Write your description here"},
                              "6008000": {"Amount": 5500, "Shared": 2, "Description": "Write your description here"},
                              "6010000": {"Amount": 0, "Shared": 12, "Description": "Write your description here"},
                              "6010001": {"Amount": 0, "Shared": 1, "Description": "Write your description here"},
                              "6010002": {"Amount": 0, "Shared": 1, "Description": "Write your description here"},
                              "6013003": {"Amount": 0, "Shared": 1, "Description": "Write your description here"},
                              "5300003": {"Amount": 441132, "Shared": 1, "Description": "Write your description here"},
                              "6006000": {"Amount": 0, "Shared": 2, "Description": "Advertisement materials"}
                             },
               "3186000162": {"5000206": {"Amount": 4302, "Shared": 2, "Description": "Write your description here"},
                              "6001000": {"Amount": 0, "Shared": 2, "Description": "Write your description here"},
                              "6005006": {"Amount": 0, "Shared": 2, "Description": "Write your description here"},
                              "6005020": {"Amount": 0, "Shared": 2, "Description": "Write your description here"},
                              "6005021": {"Amount": 20000, "Shared": 2, "Description": "Write your description here"},
                              "6005022": {"Amount": 20000, "Shared": 2, "Description": "Write your description here"},
                              "6010000": {"Amount": 20000, "Shared": 1, "Description": "Write your description here"},
                              "6010001": {"Amount": 0, "Shared": 1, "Description": "Write your description here"},
                              "6010002": {"Amount": 740000, "Shared": 1, "Description": "Write your description here"}
                             }
               }